- name: Example playbook with simple vars
  hosts: webservers
  # facts used in playbook tasks
  gather_facts: true
  # variables precedence demo
  vars: 
    # Define the stage variable
    stage: dev
  roles:
    - web
  tasks:
    - name: display facts variable
      ansible.builtin.debug:
        var: ansible_facts.architecture
    - name: copy web.html
      ansible.builtin.copy:
        src: "files/{{ stage }}_{{ ansible_facts.architecture }}_web.html"
        dest: /var/www/html/index.html
