all:
  hosts:
    node3:
      # ansible_host: ...
      # ansible_user: ...
      # ansible_ssh_pass: ...
      # ansible_ssh_port: ...
      # ansible_ssh_pass: vault ....
      # ansible_ssh_keyfile: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # /!\ Change me 

  children:
    webservers:
      hosts:
        node3: