---
########################################
# WEBSERVER ROLE - DEFAULT VARIABLES
########################################
# This file contains default values for variables used in the webserver role
#
# VARIABLE PRECEDENCE IN ANSIBLE (from lowest to highest priority):
# 1. role defaults (THIS FILE) - lowest priority
# 2. inventory file or script group vars
# 3. inventory group_vars/all
# 4. playbook group_vars/all
# 5. inventory group_vars/*
# 6. playbook group_vars/*
# 7. inventory file or script host vars
# 8. inventory host_vars/*
# 9. playbook host_vars/*
# 10. host facts / cached set_facts
# 11. play vars
# 12. play vars_prompt
# 13. play vars_files
# 14. role vars (in vars/main.yml) - higher priority than defaults
# 15. block vars
# 16. task vars
# 17. include_vars
# 18. set_facts / registered vars
# 19. role (and include_role) params
# 20. include params
# 21. extra vars (from command line -e) - highest priority
#
# BEST PRACTICE:
# - Use defaults/ for variables that users might want to override
# - Use vars/ for variables that should rarely change

# Web server document root directory
# This is where Apache will serve files from
web_document_root: /var/www/html

# Apache service name (same on both Debian and Alpine)
apache_service_name: apache2

# Default file permissions for the document root
# Using string format to preserve leading zero (octal notation)
web_directory_mode: '0755'

# You can override these variables by:
# - Setting them in your playbook's vars: section
# - Setting them in inventory (group_vars or host_vars)
# - Passing them on command line: ansible-playbook playbook.yml -e "web_document_root=/var/www/myapp"
