---

# WEB SERVER
- hosts: web
  become: true
  vars_files: vars/main.yml

  tasks:
  - name: install apache and php last version
    apt:
      name:
        - apache2
        - php
        - php-mysql
      state: present
      update_cache: yes

  - name: Give writable mode to http folder
    # Create the web server document root directory
    # Sets up /var/www/html with proper permissions (755) for web content
    # This ensures the directory exists and is accessible by the web server
    # ansible.builtin.file:
      # path: /var/www/html
      # ...

  - name: remove default index.html
    # Remove the default index.html file from the web server document root
    # This task must delete /var/www/html/index.html to prepare for custom content deployment
    # ansible.builtin.file:
      # ...

  - name: upload web app source
    # Copy application files from local app/ directory to web server document root
    # so copy app/ to /var/www/html/
    # ansible.builtin.copy:
      # src: ...
      # dest: ...

  - name: deploy php database config
    # Deploy PHP database configuration file from ansible jinja template
    # This creates db-config.php in the web root with database connection parameters
    # The template will be populated with variables like mysql_dbname, mysql_user, etc.
    # ansible.builtin.template:
      # src: ... my local jinja config file
      # dest: "/var/www/html/db-config.php"
  
  - name: ensure apache service is start
    # Start and enable the Apache2 web server service
    # This task ensures that:
    # - Apache2 service is started (running)
    # - Apache2 service is enabled to start automatically on system boot
    # ansible.builtin.service:
      # name: ...
      # state: ...
      # ...


# DATABASE SERVER

- hosts: db
  become: true
  vars_files: vars/main.yml
  vars:
    root_password: "my_secret_password"

  tasks:
  - name: install mysql
    apt:
      name: 
        - mysql-server
        - python-mysqldb # for mysql_db and mysql_user modules
      state: present
      update_cache: yes  

  - name: Create MySQL client config
    copy:
      dest: "/root/.my.cnf"
      content: |
        [client]
        user=root
        password={{ root_password }}
      mode: 0400

  - name: Allow external MySQL connections (1/2)
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^skip-external-locking'
      line: "# skip-external-locking"
    notify: Restart mysql

  - name: Allow external MySQL connections (2/2)
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: "# bind-address"
    notify: Restart mysql

  - name: upload sql table config
    template:
      src: "table.sql.j2"
      dest: "/tmp/table.sql"

  - name: add sql table to database
    mysql_db:
      name: "{{ mysql_dbname }}"
      state: present
      login_user: root
      login_password: '{{ root_password }}'
      state: import 
      target: /tmp/table.sql

  - name: "Create {{ mysql_user }} with all {{ mysql_dbname }} privileges"
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: "{{ mysql_dbname }}.*:ALL"
      host: "{{ webserver_host }}"
      state: present
      login_user: root
      login_password: '{{ root_password }}'
      login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

