---
stage: dev
version: "3.11"

# Connection variables
node_host: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31646662616237613764346235353461326663393434356363666637636438363136393232666130
  6633366339333836633763656538363163636239636438370a663230663330643238333331653937
  30333438306661313639663265326632376362653136363161333064313766653032373338653838
  3531623837353236330a313036373137643165636262626631613233333063636539343532383835
  6361
node_user: root
node_ssh_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63623034393861346431623262383139633432666162346331633832306562383235626438383738
  3037306433373035393934616336356232376438633434620a336535623436393237656531356431
  34653366363136353631353062343333663936366666343937303538636161616439383931346264
  6234643334356137350a613062656431616164383663663963333230393631336338373166653330
  3466
node_ssh_port: 2212