---
- name: Install apache
  ansible.builtin.apt:
    name: apache2
    state: present
- name: Ensure apache is running
  ansible.builtin.service:
    name: apache2
    state: started
- name: ensure web folder is present
  ansible.builtin.file:
    path: /var/www/html
    state: directory