  tasks:
  - name: install apache and php last version
    ansible.builtin.apt:
      name:
        - apache2
        - php
        - php-mysql
      state: present
      update_cache: yes

  - name: Give writable mode to http folder
    ansible.builtin.file:
      path: /var/www/html
      state: directory
      mode: '0755'

  - name: remove default index.html
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: upload web app source
    ansible.builtin.copy:
      src: app/
      dest: /var/www/html/

  - name: deploy php database config
    ansible.builtin.template:
      src: db-config.php.j2
      dest: /var/www/html/db-config.php
  
  - name: ensure apache service is start
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
